using Oscar
using Random

# ============================================================
# Z conventions
# ============================================================

const ZElem = ZZRingElem
const PInt  = Union{Int, ZZRingElem}        # accepted "p" argument types

# ============================================================
# 0) Primes (p ≡ 11 mod 12)
#
#    What the arithmetic here actually needs is p ≡ 3 (mod 4): that is
#    exactly when -1 is a non-residue mod p, so B_{p,∞} is the algebra
#    ramified at p and ∞ generated by i^2=-1, j^2=-p, and
#    O = Z + Zi + Z(i+j)/2 + Z(1+ij)/2 is a maximal order with the
#    clean reduced norm form used by nrd_q below. The extra condition
#    p ≡ 2 (mod 3) plays no role in any of that.
#
#    We nevertheless require the stronger p ≡ 11 (mod 12) for
#    compatibility: it is the convention used by polz_all.jl and by
#    every prime in data/, so the two scripts accept the same inputs.
#    Relaxing to p ≡ 3 (mod 4) would additionally admit p = 7, 19, 31,
#    43, ... and would not require any change to the code below.
# ============================================================

"""
    check_p_11mod12(p) -> ZZRingElem

Validate that p ≡ 11 (mod 12) and (probably) prime, returning p as a
ZZRingElem. Accepts Int or ZZRingElem so it works for both small test
primes and cryptographic-size primes (p can be thousands of bits,
e.g. p = 2^721 * 3^176 - 1).
"""
function check_p_11mod12(p::PInt)
    pZ = ZZ(p)
    is_probable_prime(pZ) || error("p must be prime; got p=$pZ")
    mod(pZ, 12) == 11 || error("p must be 11 mod 12; got p mod 12 = $(mod(pZ,12))")
    return pZ
end

# ============================================================
# 1) Thread-safe uniform random integers
#
#    Draws from a caller-supplied Julia AbstractRNG rather than Nemo's
#    global FLINT random state. Nemo.rand_bits (and Nemo's ECM code
#    reached through `factor`) indexes a shared pool by
#    Threads.threadid():
#
#        Nemo/src/flint/fmpz.jl:3102
#            _flint_rand_states[Threads.threadid()]
#
#    and that pool is sized to Threads.nthreads() at Nemo's __init__
#    (Nemo/src/Nemo.jl:455), i.e. to the *default* pool only. Tasks
#    spawned by Threads.@threads run on threadids offset past the
#    interactive pool, so with `-t 4,1` they occupy ids 2..5 indexing a
#    4-element vector. This is deterministic, not a scheduling fluke:
#
#        BoundsError: attempt to access 4-element Vector{Nemo.rand_ctx}
#                     at index [5]
#
#    A per-task Random.Xoshiro has no such shared state, so it is safe
#    by construction. (`sum_two_squares` still reaches Nemo's `factor`,
#    which has the same problem plus an unsynchronised `big_primes`
#    global; see FACTOR_LOCK below.)
# ============================================================

"""
    rand_below(rng, N::ZZRingElem) -> ZZRingElem

Uniform random integer in [0, N] (inclusive at both ends), drawn from
`rng`.

Pass `Nbig` when calling in a loop with a fixed bound: converting the
`ZZRingElem` bound to `BigInt` is the only per-call overhead worth
hoisting, and every hot caller here does so.
"""
rand_below(rng::AbstractRNG, N::ZElem)::ZElem = rand_below(rng, BigInt(N))

function rand_below(rng::AbstractRNG, N::BigInt)::ZElem
    N < 0 && error("rand_below: require N ≥ 0, got $N")
    iszero(N) && return ZZ(0)
    # Random's BigInt range sampler fills limbs directly and allocates one
    # result, versus ~2 finalizer-bearing ZZRingElem per 64-bit word for a
    # shift/add reconstruction. That garbage is a global GC serialisation
    # point, so it caps thread scaling long before it shows up as serial cost.
    return ZZ(rand(rng, big(0):N))
end

# ============================================================
# 2) Quaternion order element type
#
#    B_{p,∞} = Q + Qi + Qj + Qij with i^2 = -1, j^2 = -p, ij = -ji.
#    The maximal order O has Z-basis [1, i, (i+j)/2, (1+ij)/2]. An
#    element is stored here in "half-coordinates" (A0,A1,A2,A3) via
#        a = (A0 + A1 i + A2 j + A3 ij) / 2,
#    related to the basis coordinates (w,x,y,z) of to_wxyz by
#    A0 = 2w+z, A1 = 2x+y, A2 = y, A3 = z. Membership in O is exactly
#    the parity condition A0 ≡ A3 and A1 ≡ A2 (mod 2) used throughout
#    by in_order/to_wxyz.
# ============================================================

struct QEltZZ
    A0::ZElem
    A1::ZElem
    A2::ZElem
    A3::ZElem
end

"""
    _is_even(x::ZZRingElem) -> Bool

Test whether `x` is even.

Deliberately underscore-prefixed: Oscar exports `is_even` (an alias for
`Base.iseven`), and defining an unprefixed `is_even` here would replace
that binding in `Main` with a one-method function, breaking `is_even`
for every other type in an `include()`-ing session.
"""
_is_even(x::ZElem) = iszero(mod(x, 2))

"""
    in_order(a::QEltZZ) -> Bool

Test whether the half-coordinates of `a` satisfy the parity condition
(A0 ≡ A3 and A1 ≡ A2 mod 2) that puts `a` in the maximal order O.
"""
in_order(a::QEltZZ) = _is_even(a.A0 - a.A3) && _is_even(a.A1 - a.A2)

"""
    nrd_q(a::QEltZZ, p) -> ZZRingElem

Reduced norm nrd(a) = (A0² + A1² + p(A2² + A3²)) / 4.
"""
function nrd_q(a::QEltZZ, p::PInt)::ZElem
    pZ = ZZ(p)
    num = a.A0*a.A0 + a.A1*a.A1 + pZ*(a.A2*a.A2 + a.A3*a.A3)
    iszero(mod(num, 4)) || error("nrd_q(QEltZZ): numerator not divisible by 4")
    return div(num, 4)
end

"""
    to_wxyz(a::QEltZZ) -> (w,x,y,z)

Convert half-coordinates to coordinates in the order basis
[1, i, (i+j)/2, (1+ij)/2], i.e. a = w + xi + y(i+j)/2 + z(1+ij)/2.
"""
function to_wxyz(a::QEltZZ)
    A0,A1,A2,A3 = a.A0,a.A1,a.A2,a.A3
    _is_even(A0 - A3) || error("to_wxyz(QEltZZ): parity fail (A0-A3 odd); not in O")
    _is_even(A1 - A2) || error("to_wxyz(QEltZZ): parity fail (A1-A2 odd); not in O")
    z = A3
    y = A2
    w = div(A0 - z, 2)
    x = div(A1 - y, 2)
    return (w,x,y,z)
end

"""
    Hermitian2x2ZZ

A polarization: the Hermitian matrix [u a; ā v] over O with u,v ∈ Z,
a ∈ O, representing a positive-definite unimodular Hermitian form.
Unimodularity is det = uv - nrd(a) = 1, checked by det_unimodular_ok.
"""
struct Hermitian2x2ZZ
    u::ZElem
    a::QEltZZ
    v::ZElem
end

"""
    det_unimodular_ok(H::Hermitian2x2ZZ, p) -> Bool

Test whether `H` is unimodular, i.e. det(H) = u·v - nrd(a) = 1.
"""
det_unimodular_ok(H::Hermitian2x2ZZ, p::PInt) = (H.u*H.v - nrd_q(H.a, p) == 1)

# ============================================================
# 3) Sum of two squares via Gaussian integers
#
#    n = x²+y² is solvable iff every prime ≡ 3 (mod 4) divides n to
#    an even power. The decomposition is built multiplicatively in
#    Z[i] via the Brahmagupta–Fibonacci identity
#        (a²+b²)(c²+d²) = (ac-bd)² + (ad+bc)²,
#    using 2 = -i(1+i)², p ≡ 3 (mod 4) prime (irreducible, contributes
#    p^(e/2) on the real axis), and p ≡ 1 (mod 4) prime (splits as
#    ππ̄, with π = x+iy found via Cornacchia from a square root of -1
#    mod p).
#
#    Nemo's factor(::ZZRingElem) is NOT safe to call concurrently: its
#    ECM path indexes _flint_rand_states / _ecm_B1s / _ecm_nCs by
#    Threads.threadid() (Nemo/src/flint/fmpz_factor.jl:77-91, the same
#    out-of-bounds hazard documented in section 1), and it both reads
#    and push!es an unsynchronised `big_primes::Vector{ZZRingElem}`
#    global (fmpz_factor.jl:132-163). FACTOR_LOCK serialises it. This
#    costs nothing in practice: the factor fallback is only reachable
#    for small rhs (see factor_digit_cutoff), while the Cornacchia fast
#    path that dominates every realistic run never takes the lock.
# ============================================================

"""
    FACTOR_LOCK

Serialises calls into Nemo's `factor`, which carries thread-unsafe
global state. See the section comment above.
"""
const FACTOR_LOCK = ReentrantLock()

"""
    gauss_mul(a, b, c, d) -> (re, im)

Multiply Gaussian integers (a+bi)(c+di), returning the result as a
(real, imaginary) coordinate pair.
"""
gauss_mul(a::ZElem, b::ZElem, c::ZElem, d::ZElem) = (a*c - b*d, a*d + b*c)

"""
    gauss_pow(a, b, e::Int) -> (re, im)

Raise the Gaussian integer a+bi to the non-negative integer power `e`
by binary exponentiation, returning the result as a coordinate pair.
"""
function gauss_pow(a::ZElem, b::ZElem, e::Int)
    ra, rb = ZZ(1), ZZ(0)
    ba, bb = a, b
    k = e
    while k > 0
        if isodd(k)
            ra, rb = gauss_mul(ra, rb, ba, bb)
        end
        ba, bb = gauss_mul(ba, bb, ba, bb)
        k >>= 1
    end
    return (ra, rb)
end

"""
    cornacchia_two_squares(q::ZZRingElem; check_prime=true) -> (x, y)

Solve x² + y² = q for prime q ≡ 1 (mod 4). Take a square root t of -1
mod q, then run the Euclidean algorithm on (q, t) until the remainder
r satisfies r² < q; this r is x, and y = √(q - x²). `check_prime`
controls whether q's primality is (re-)verified via
`is_probable_prime` before running the above.
"""
function cornacchia_two_squares(q::ZElem; check_prime::Bool=true)
    mod(q, 4) == 1 || error("Cornacchia: need q ≡ 1 (mod 4), got q=$q")
    if check_prime
        is_probable_prime(q) || error("Cornacchia: modulus must be prime, got q=$q")
    end
    t = sqrtmod(ZZ(-1), q)
    r0, r1 = q, t
    while r1*r1 > q
        r0, r1 = r1, mod(r0, r1)
    end
    x = r1
    y2 = q - x*x
    y = isqrt(y2)
    y*y == y2 || error("Cornacchia failed for q=$q")
    return (x, y)
end

"""
    sum_two_squares(n::ZZRingElem) -> Union{Tuple, Nothing}

Find `(x, y)` with `x² + y² = n`, or `nothing` if no such pair exists.
Requires fully factoring `n` (via `factor`), so this is only cheap for
small or smooth `n`; callers gate its use accordingly (see
`allow_factor` in `represent_integer_in_O`).

The `factor` call is serialised through `FACTOR_LOCK` (see below); the
surrounding Gaussian-integer arithmetic is pure and stays parallel.
"""
function sum_two_squares(n::ZElem)
    n < 0 && return nothing
    iszero(n) && return (ZZ(0), ZZ(0))
    fac = lock(FACTOR_LOCK) do
        factor(n)
    end
    a, b = ZZ(1), ZZ(0)
    for (pp, e0) in fac
        e = Int(e0)
        if pp == 2
            x, y = gauss_pow(ZZ(1), ZZ(1), e)
            a, b = gauss_mul(a, b, x, y)
        else
            r = mod(pp, 4)
            if r == 3
                isodd(e) && return nothing
                a, b = gauss_mul(a, b, pp^(e ÷ 2), ZZ(0))
            elseif r == 1
                x, y = cornacchia_two_squares(pp)
                x, y = gauss_pow(x, y, e)
                a, b = gauss_mul(a, b, x, y)
            else
                error("unexpected prime residue mod 4 for p=$pp")
            end
        end
    end
    return (abs(a), abs(b))
end

# ============================================================
# 4) RepresentInteger: probabilistic solver for r ∈ O with nrd(r) = N
#
#    Kohel–Lauter–Petit–Tignol / SQIsign-style RepresentInteger.
#    Writing r = (A0+A1 i+A2 j+A3 ij)/2, the norm equation
#    nrd(r) = (A0²+A1²+p(A2²+A3²))/4 = N becomes, for random A2,A3,
#        A0² + A1² = 4N - p(A2²+A3²) =: rhs.
#    By Fermat's two-squares theorem, rhs is a sum of two squares
#    whenever rhs ≡ 1 (mod 4) and is prime, in which case Cornacchia's
#    algorithm recovers A0,A1 directly in O(log² rhs) time — far
#    cheaper than factoring rhs in general. Sampling (A2,A3) inside
#    the disk of radius B = ⌊√(4N/p)⌋ keeps rhs > 0; heuristically a
#    constant fraction of samples land on a prime rhs ≡ 1 (mod 4), so
#    O(log p) retries succeed with overwhelming probability.
#
#    Parity: with p ≡ 3 (mod 4), A2²+A3² is 0, 1 or 2 mod 4 according as
#    A2,A3 are both even, opposite parity, or both odd, so
#        rhs = 4N - p(A2²+A3²) ≡ 0, 1, 2 (mod 4)
#    respectively. The fast path's `rhs ≡ 1 (mod 4)` test therefore holds
#    for exactly the opposite-parity samples — a fact known before rhs is
#    ever computed. When the factor fallback cannot fire (see below) we
#    sample that parity directly instead of discarding half the draws.
#    Same-parity samples are still reachable through the factor fallback
#    (both even needs A0,A1 both even, rhs ≡ 0; both odd needs A0,A1 both
#    odd, rhs ≡ 2), so the restriction is applied only when that fallback
#    is provably dead for this call.
# ============================================================

"""
    RepresentIntegerFailure

Raised when `represent_integer_in_O` exhausts its retry budget, or is
handed parameters for which no solution is reachable. Callers that
retry with a fresh sample (see `generate_polarizations`) match on this
type; anything else escaping `represent_integer_in_O` is a real bug and
must propagate.
"""
struct RepresentIntegerFailure <: Exception
    msg::String
end

Base.showerror(io::IO, e::RepresentIntegerFailure) =
    print(io, "RepresentInteger: ", e.msg)

"""
    rand_even_pm(rng, B) -> ZZRingElem

Uniform *even* integer in [-B, B], i.e. 2u for u uniform in
[-⌊B/2⌋, ⌊B/2⌋].
"""
function rand_even_pm(rng::AbstractRNG, B::ZElem)
    h = div(B, 2)
    return 2*(rand_below(rng, BigInt(2*h)) - h)
end

"""
    rand_odd_pm(rng, B) -> ZZRingElem

Uniform *odd* integer in [-B, B], i.e. 2u+1 for u uniform in
[-⌈B/2⌉, ⌊(B-1)/2⌋]. Requires B ≥ 1 (no odd integer lies in [0,0]).
"""
function rand_odd_pm(rng::AbstractRNG, B::ZElem)
    lo = -div(B + 1, 2)
    hi = div(B - 1, 2)
    return 2*(lo + rand_below(rng, BigInt(hi - lo))) + 1
end

"""
    represent_integer_in_O(N, p; rng=Random.default_rng(), max_tries=1200,
                           allow_factor=false, factor_digit_cutoff=50) -> QEltZZ

Solve nrd(r) = N for r ∈ O by random sampling + Cornacchia (fast
path), falling back to full factorization of `rhs` via
`sum_two_squares` when `allow_factor` is set or `rhs` has at most
`factor_digit_cutoff` decimal digits.

Throws [`RepresentIntegerFailure`](@ref) if no solution is found within
`max_tries` samples.
"""
function represent_integer_in_O(N::ZElem, p::PInt;
                                rng::AbstractRNG=Random.default_rng(),
                                max_tries::Int=1200,
                                allow_factor::Bool=false,
                                factor_digit_cutoff::Int=50)::QEltZZ
    N > 0 || throw(RepresentIntegerFailure("need N>0, got N=$N"))
    pZ = ZZ(p)
    fourN = 4*N
    B = isqrt(div(fourN, pZ))  # floor sqrt(4N/p)

    # When 4N already exceeds the digit cutoff, the factor fallback is dead
    # weight: rhs only drops under the cutoff when p(A2²+A3²) lands within a
    # relative band of ~10^cutoff/4N of 4N, which for cryptographic N is a
    # vanishing fraction of samples. Deciding this once here (rather than per
    # sample) is what licenses the parity restriction below, since the samples
    # it excludes are reachable only through that fallback.
    factor_path_dead = !allow_factor && fourN > ZZ(10)^factor_digit_cutoff

    if iszero(B)
        # 4N < p forces A2 = A3 = 0, so every retry recomputes the identical
        # rhs = 4N ≡ 0 (mod 4) and the fast path can never fire.
        factor_path_dead && throw(RepresentIntegerFailure(
            "4N < p (B=0) with the factor fallback disabled: no solution is " *
            "reachable and every retry would recompute the same rhs. " *
            "Increase sbound, or pass allow_factor=true."))
    end

    twoBbig = BigInt(2*B)   # hoisted: the bound is fixed across all retries

    for _ in 1:max_tries
        local A2, A3
        if iszero(B)
            A2 = ZZ(0); A3 = ZZ(0)
        elseif factor_path_dead
            # Only opposite-parity (A2,A3) can yield rhs ≡ 1 (mod 4); pick
            # which coordinate carries the even value uniformly at random.
            if rand(rng, Bool)
                A2 = rand_even_pm(rng, B); A3 = rand_odd_pm(rng, B)
            else
                A2 = rand_odd_pm(rng, B);  A3 = rand_even_pm(rng, B)
            end
        else
            A2 = rand_below(rng, twoBbig) - B
            A3 = rand_below(rng, twoBbig) - B
        end

        rhs = fourN - pZ*(A2*A2 + A3*A3)
        rhs <= 0 && continue

        # ---- FAST PATH: Cornacchia on a probable-prime rhs ----
        if mod(rhs, 4) == 1 && is_probable_prime(rhs)
            try
                A0, A1 = cornacchia_two_squares(rhs; check_prime=false)

                if _is_even(A0 - A3) && _is_even(A1 - A2)
                    r = QEltZZ(A0, A1, A2, A3)
                    (in_order(r) && nrd_q(r, pZ) == N) && return r
                elseif _is_even(A1 - A3) && _is_even(A0 - A2)
                    r = QEltZZ(A1, A0, A2, A3)
                    (in_order(r) && nrd_q(r, pZ) == N) && return r
                end
            catch
                # sqrtmod failed / Cornacchia failed
            end
        end

        # ---- OPTIONAL FACTOR FALLBACK (opt-in; full factorization) ----
        if !factor_path_dead &&
           (allow_factor || (Int(flog(rhs, 10)) + 1 <= factor_digit_cutoff))
            xy = sum_two_squares(rhs)
            xy === nothing && continue
            A0, A1 = xy

            if _is_even(A0 - A3) && _is_even(A1 - A2)
                r = QEltZZ(A0, A1, A2, A3)
                nrd_q(r, pZ) == N && return r
            elseif _is_even(A1 - A3) && _is_even(A0 - A2)
                r = QEltZZ(A1, A0, A2, A3)
                nrd_q(r, pZ) == N && return r
            end
        end
    end

    throw(RepresentIntegerFailure(
        "failed after $max_tries tries. Increase max_tries or restarts " *
        "(or allow_factor=true)."))
end

# ============================================================
# 5) Random polarization sampling
#
#    Samples s ∈ [1, p^sbound] and t ∈ [1, p^(3·sbound)], sets
#    N = st - 1, and solves nrd(r) = N in O via represent_integer_in_O.
#    Then [s r; r̄ t] is Hermitian with det = st - nrd(r) = 1, i.e. a
#    unimodular (positive-definite) polarization. sbound controls the
#    size of s,t and hence, via N ≈ st, the size of the norm equation
#    represent_integer_in_O must solve; the t-bound is cubed in s so
#    that N ranges widely relative to p, keeping the Cornacchia fast
#    path's prime-density heuristic effective.
# ============================================================

"""
    random_polarization(pZ; sbound=20, rng=Random.default_rng(),
                        max_tries=1200, allow_factor=false) -> Hermitian2x2ZZ

Sample a random unimodular polarization [s r; r̄ t] over O with
nrd(r) = st - 1, for `pZ` a validated prime ≡ 11 (mod 12).
"""
function random_polarization(pZ::ZElem; sbound::Int=20,
                            rng::AbstractRNG=Random.default_rng(),
                            max_tries::Int=1200,
                            allow_factor::Bool=false)::Hermitian2x2ZZ

    smax = pZ^sbound
    tmax = pZ^(3*sbound)

    # BigInt(...) once per bound rather than once per draw inside rand_below.
    s = isone(smax) ? ZZ(1) : (ZZ(1) + rand_below(rng, BigInt(smax - 1)))
    t = isone(tmax) ? ZZ(1) : (ZZ(1) + rand_below(rng, BigInt(tmax - 1)))

    N = s*t - 1
    r = represent_integer_in_O(N, pZ; rng=rng, max_tries=max_tries, allow_factor=allow_factor)

    H = Hermitian2x2ZZ(s, r, t)
    det_unimodular_ok(H, pZ) || error("internal: det != 1")
    return H
end

# ============================================================
# 6) Parameter heuristics
#
#    sbound itself (see random_polarization) has no single correct
#    value: it sets N ≈ p^(4·sbound) via s ∈ [1,p^sbound],
#    t ∈ [1,p^(3·sbound)], so the norm equation RepresentInteger must
#    solve grows like 4·sbound·bits(p) bits. suggest_sbound below
#    picks the largest sbound keeping that roughly within
#    `target_bits`, so the search stays a comparable, tractable size
#    whether p is an 8-bit test prime (sbound near 20) or a
#    thousand-bit cryptographic prime (sbound near 1).
#
#    Once sbound is fixed, the Cornacchia fast path in RepresentInteger
#    succeeds on a sample when rhs lands prime and ≡ 1 (mod 4); by the
#    prime number theorem this happens for a Θ(1/log p) fraction of
#    samples, so expected tries to succeed scale like O(log p).
#    suggest_params applies a constant-factor safety margin on top of
#    that estimate, sized by sbound and p's bit length.
# ============================================================

"""
    suggest_sbound(p; target_bits=1600) -> Int

Heuristic default for `--sbound` when the user doesn't supply one:
the largest sbound with N ≈ p^(4·sbound) staying within roughly
`target_bits` bits, clamped to [1, 20].

Note the lower clamp wins for large p and `target_bits` is then
exceeded: the 1000-bit p = 2^721*3^176-1 yields sbound = 1 and hence
N ≈ 4000 bits, 2.5x over a 1600-bit target. sbound = 1 is already the
smallest value
that keeps s, t non-trivial, so there is nothing below it to pick;
lower the exponent on the t-bound in `random_polarization` if the norm
equation needs to be smaller than that.
"""
function suggest_sbound(p::PInt; target_bits::Int=1600)::Int
    pZ = ZZ(p)
    bits = ndigits(pZ, base=2)
    sbound = max(1, round(Int, target_bits / (4*bits)))
    return min(sbound, 20)
end

"""
    suggest_params(p; sbound=20, mode=:balanced) -> (; bits, sbound, max_tries)

Heuristic `max_tries` for RepresentInteger, scaled from p's bit length
and `sbound`. `mode` trades retry budget against how eagerly a caller
gives up on a sample and restarts with fresh s,t: `:fast` retries least,
`:few_restarts` most, `:balanced` in between.
"""
function suggest_params(p::PInt; sbound::Int=20, mode::Symbol=:balanced)
    pZ = ZZ(p)
    bits = ndigits(pZ, base=2)
    etries = ceil(Int, 6 * sbound * bits)   # expected-tries estimate, O(log p)

    max_tries = if mode == :fast
        max(800, etries)
    elseif mode == :few_restarts
        max(2000, 5 * etries)
    else
        max(1200, 3 * etries)
    end

    return (; bits, sbound, max_tries)
end

# ============================================================
# 7) Batch generation of N random polarizations — PARALLEL
#
#    Each random_polarization draw is statistically independent, so
#    the N draws are embarrassingly parallel across threads, each
#    with its own RNG. p is validated once and threaded through
#    rather than re-checked per sample. Distinctness is tracked via
#    a single shared Set of ZZRingElem tuples (no string conversion
#    in the hot path), guarded by a lock. That lock is only held for
#    the cheap dedup/accumulate/callback step, never around the
#    expensive random_polarization call, so threads don't contend
#    with each other while doing the actual work. Because the callback
#    runs inside that same lock, a caller-supplied `on_new_result` can
#    write each result out (e.g. to disk, flushed) the moment it's
#    accepted, without needing any locking of its own.
# ============================================================

"""
    generate_polarizations(p, N; sbound=20, max_tries=nothing, allow_factor=false,
                           base_seed=nothing, max_attempts_per_slot=200,
                           on_new_result=nothing) -> Vector{Hermitian2x2ZZ}

Generate N distinct random polarizations for prime p, in parallel
across all available Julia threads. Start Julia itself with
`--threads auto` (or `-t auto`) to use all cores — Julia fixes its
thread count at process start, so this cannot be set from inside the
script.

Threading is worth using here. Measured on a 24-core machine, 400
polarizations for a 257-bit p:

    threads    1      2      4      8     24
    wall     88.9s  44.7s  26.0s  16.0s  11.6s
    speedup    --   1.99x  3.42x  5.57x  7.67x

Scaling is near-linear to 8 threads and still worth taking to 24. Note
this depends on `rand_below` staying allocation-light: garbage forces
global GC pauses, and an earlier word-at-a-time implementation flattened
the curve past 4 threads (59% of wall time in GC at 24) while barely
affecting single-threaded cost.

`base_seed` makes a run reproducible **only single-threaded**. With more
than one thread, which samples get accepted depends on the race between
threads and the shared result-count check, so runs with the same seed
differ. Use `-t 1` when you need an exact rerun.

If `on_new_result` is given, it is called as `on_new_result(idx, H)`
for every newly-accepted, globally-distinct polarization `H` (1-indexed
in the order it was accepted), immediately as it's found and while
still holding the internal lock — so it's safe to write straight to an
IO stream from inside the callback without extra synchronization.
"""
function generate_polarizations(p::PInt, N::Int;
                                sbound::Int=20,
                                max_tries::Union{Nothing,Int}=nothing,
                                allow_factor::Bool=false,
                                base_seed::Union{Nothing,Int}=nothing,
                                max_attempts_per_slot::Int=200,
                                on_new_result::Union{Nothing,Function}=nothing)
    N > 0 || error("generate_polarizations: N must be positive; got N=$N")

    pZ = check_p_11mod12(p)  # validated once, threaded through every sample

    max_tries_resolved::Int = if max_tries === nothing
        suggest_params(pZ; sbound=sbound, mode=:balanced).max_tries
    else
        max_tries
    end

    nthreads = Threads.nthreads()

    # Independently seeded per-task RNGs. Note this makes each task's *stream*
    # deterministic, but not the run as a whole: which samples win the race to
    # be accepted still varies, so identical seeds reproduce exactly only at
    # nthreads == 1. See the docstring.
    seed0 = base_seed === nothing ? rand(RandomDevice(), 1:typemax(Int)) : base_seed
    thread_rngs = [Random.Xoshiro(seed0 + 7919*k) for k in 1:nthreads]

    # Shared state, all protected by `reslock`: `seen` for dedup, `all_results`
    # for the final return value, and (if given) `on_new_result` so each
    # newly-accepted, globally-distinct sample is reported/written exactly
    # once, in assignment order, as soon as it's found — not just after every
    # thread finishes. The lock is only held for this short bookkeeping
    # step; the expensive part (random_polarization) runs lock-free.
    reslock = ReentrantLock()
    seen = Set{NTuple{6,ZElem}}()
    all_results = Hermitian2x2ZZ[]

    # Global attempt budget shared across threads (not per-thread), since
    # with global dedup+counting a thread may need to do more or less than
    # N/nthreads work depending on how other threads fare.
    global_attempts = Threads.Atomic{Int}(0)
    max_global_attempts = N * max_attempts_per_slot + 16 * nthreads

    Threads.@threads for tid in 1:nthreads
        rng = thread_rngs[tid]

        while true
            enough = lock(reslock) do
                length(all_results) >= N
            end
            enough && break

            na = Threads.atomic_add!(global_attempts, 1) + 1
            na <= max_global_attempts ||
                error("generate_polarizations: exceeded global attempt budget; increase max_attempts_per_slot")

            local H
            try
                H = random_polarization(pZ; sbound=sbound, rng=rng,
                                       max_tries=max_tries_resolved, allow_factor=allow_factor)
            catch err
                # A sample that exhausted its retry budget is routine: draw
                # fresh s,t and carry on. Anything else is a real bug and must
                # propagate. Matching on the type (rather than on the rendered
                # message) keeps a reworded error from silently becoming fatal.
                err isa RepresentIntegerFailure && continue
                rethrow()
            end

            key = (H.u, H.v, H.a.A0, H.a.A1, H.a.A2, H.a.A3)

            lock(reslock) do
                if length(all_results) < N && !(key in seen)
                    push!(seen, key)
                    push!(all_results, H)
                    idx = length(all_results)
                    if on_new_result !== nothing
                        on_new_result(idx, H)  # called while holding the lock:
                                                # writes/prints stay ordered
                                                # and race-free with no extra
                                                # locking needed by the caller
                    end
                end
            end
        end
    end

    return all_results
end

# ============================================================
# 8) Pretty printing and output naming
# ============================================================

"""
    SMALL_P_BITS

Bit-length below which `default_output_filename` names files by p's
decimal value ("polarizations_p23.txt") rather than by bits+digest.
25 bits sits in the empty gap between the two existing corpora under
`data/`: the small sets top out at p = 1619 (11 bits) and the big sets
start at 50 bits.
"""
const SMALL_P_BITS = 25

"""
    shortZ(x::ZZRingElem; maxchars=60) -> String

Render `x` as a decimal string, truncating the middle (with a
"(len=...)" suffix) if it would exceed `maxchars` characters.
"""
function shortZ(x::ZZRingElem; maxchars::Int=60)
    s = string(x)
    (maxchars <= 0 || lastindex(s) <= maxchars) && return s
    head = max(10, maxchars ÷ 2 - 3)
    tail = max(10, maxchars - head - 3)
    return s[1:head] * "..." * s[end-tail+1:end] * " (len=$(length(s)))"
end

"""
    default_output_filename(pZ::ZZRingElem, N::Int) -> String

Filesystem-safe default output filename, in one of two shapes matching
the conventions already used under `data/`:

  * p under `SMALL_P_BITS` (25) bits — "polarizations_p<p>.txt", p's
    decimal value verbatim, as in data/polz_small_all/ and
    data/polz_small_100k/ (e.g. "polarizations_p23.txt"). Short enough
    to stay readable, and the prime is recoverable from the name.
  * otherwise — "polz_<bits>bit_<digest>_<N>.txt", as in
    data/polz_big_10k/ (e.g. "polz_1000bit_faa1c19f_10000.txt"), where
    <bits> is p's bit length and <digest> an 8-hex-digit hash of p's
    decimal value. A 1000-bit p has ~302 digits, far too long for a
    filename, so it is identified by size plus digest instead.

Note the small form carries no N, matching the existing corpus: two
runs for the same p with different N resolve to the same default path
and the second overwrites the first. Pass `--outfile` to keep both.
"""
function default_output_filename(pZ::ZZRingElem, N::Int)::String
    bits = ndigits(pZ, base=2)
    bits < SMALL_P_BITS && return "polarizations_p$(pZ).txt"
    digest = string(hash(string(pZ)) & 0xffffffff; base=16, pad=8)
    return "polz_$(bits)bit_$(digest)_$(N).txt"
end

# ============================================================
# 9) Command-line interface
#
#    `p` is parsed via parse_p_expr (decimal or + - * ^ ( ) expression,
#    e.g. "2^721*3^176-1"). `--sbound` is optional: since
#    random_polarization's t-bound is p^(3·sbound), a value reasonable
#    for small test p (10-20) is far too large at cryptographic size
#    (1-2 there), so when omitted it's auto-picked by suggest_sbound
#    from p's bit length. See `--help` for the full option list.
# ============================================================

"""
    parse_p_expr(s::AbstractString) -> ZZRingElem

Parse `s` as either a plain decimal integer or a restricted arithmetic
expression using only digits, whitespace, and the operators + - * ^ ( ).
This intentionally does NOT call `eval`/`Meta.parse` on arbitrary input;
the grammar below is hand-rolled and rejects anything outside
{digits, + - * ^ ( ) whitespace}, so a CLI argument can never inject
arbitrary Julia code.
"""
function parse_p_expr(s::AbstractString)::ZZRingElem
    str = strip(s)
    if all(c -> isdigit(c), str)
        return ZZ(parse(BigInt, str))
    end

    allowed = Set(['0','1','2','3','4','5','6','7','8','9','+','-','*','^','(',')',' ','\t'])
    all(c -> c in allowed, str) ||
        error("parse_p_expr: p expression contains disallowed characters; only digits and + - * ^ ( ) are permitted. Got: $s")

    # Tokenize
    toks = String[]
    i = 1
    n = lastindex(str)
    while i <= n
        c = str[i]
        if isspace(c)
            i = nextind(str, i)
        elseif isdigit(c)
            j = i
            while j <= n && isdigit(str[j])
                j = nextind(str, j)
            end
            push!(toks, str[i:prevind(str,j)])
            i = j
        else
            push!(toks, string(c))
            i = nextind(str, i)
        end
    end

    pos = Ref(1)
    peek() = pos[] <= length(toks) ? toks[pos[]] : nothing
    advance!() = (t = toks[pos[]]; pos[] += 1; t)

    # Recursive-descent: expr := term (('+'|'-') term)*
    #                     term := factor (('*') factor)*
    #                     factor := unary ('^' unary)?     (right-assoc not needed here; left is fine for our use)
    #                     unary := '-' unary | atom
    #                     atom := NUMBER | '(' expr ')'
    local parse_expr, parse_term, parse_factor, parse_unary, parse_atom

    function parse_atom()
        t = peek()
        t === nothing && error("parse_p_expr: unexpected end of expression")
        if t == "("
            advance!()
            v = parse_expr()
            peek() == ")" || error("parse_p_expr: expected ')'")
            advance!()
            return v
        elseif all(isdigit, t)
            advance!()
            return ZZ(parse(BigInt, t))
        else
            error("parse_p_expr: unexpected token '$t'")
        end
    end

    function parse_unary()
        if peek() == "-"
            advance!()
            return -parse_unary()
        end
        return parse_atom()
    end

    function parse_factor()
        v = parse_unary()
        while peek() == "^"
            advance!()
            e = parse_unary()
            e >= 0 || error("parse_p_expr: negative exponents not supported")
            v = v^Int(e)
        end
        return v
    end

    function parse_term()
        v = parse_factor()
        while peek() == "*"
            advance!()
            v = v * parse_factor()
        end
        return v
    end

    function parse_expr()
        v = parse_term()
        while peek() in ("+", "-")
            op = advance!()
            rhs = parse_term()
            v = op == "+" ? v + rhs : v - rhs
        end
        return v
    end

    result = parse_expr()
    pos[] <= length(toks) && error("parse_p_expr: trailing tokens after expression: $(toks[pos[]:end])")
    return result
end

const HELP_TEXT = """
Usage:
  julia --threads auto polz_random.jl <p> <N> [options]

Positional arguments:
  <p>    Prime p (≡ 11 mod 12). Either a plain decimal integer, or an
         arithmetic expression using digits and + - * ^ ( ), e.g.
         "2^721*3^176-1" (quote it in the shell).
  <N>    Number of distinct random polarizations to generate (positive integer).

Optional options:
  --sbound S             Search-bound exponent (see random_polarization).
                          Default: auto-picked from p's bit length via
                          suggest_sbound (large for small test p, small
                          for cryptographic-size p). Pass explicitly to
                          override.
  --outfile PATH         Output file path
                          (default: polz_<bits>bit_<digest>_<N>.txt)
  --max-tries K          Max RepresentInteger attempts per sample
                          (default: auto-computed from p's bit length)
  --seed S               Base RNG seed (integer). Reproduces a run exactly
                          only when running single-threaded (`-t 1`); with
                          more threads the accepted samples depend on
                          inter-thread timing. Default: a fresh OS-random
                          seed each run.
  --allow-factor          Force the full-factorization fallback in
                          RepresentInteger on for every sample (can be very
                          slow / inappropriate at cryptographic size).
                          NOTE: even without this flag the fallback runs
                          automatically whenever rhs has at most 50 decimal
                          digits, which is reachable for small p with a
                          small --sbound.
  -h, --help              Show this help and exit.

Note: to use multiple threads, pass `--threads auto` (or `-t auto` /
`-t N`) to the `julia` executable itself, BEFORE the script name.
Julia's thread count is fixed at process start, so this script cannot
set or change it once running:
  julia --threads auto polz_random.jl <p> <N> [options]

Threading pays off: 400 polarizations at a 257-bit p took 88.9s on 1
thread, 26.0s on 4 and 11.6s on 24 (7.7x). If JULIA_NUM_THREADS is set
in your environment you already get that many without passing -t.

Examples:
  julia --threads auto polz_random.jl 23 50
  julia --threads auto polz_random.jl "2^721*3^176-1" 100 \\
        --outfile sqisign_pols.txt --seed 12345
"""

struct CLIArgs
    p_str::String
    N::Int
    sbound::Union{Nothing,Int}
    outfile::Union{Nothing,String}
    max_tries::Union{Nothing,Int}
    seed::Union{Nothing,Int}
    allow_factor::Bool
end

# Print HELP_TEXT and exit the process with the given status code.
function print_help_and_exit(code::Int=0)
    print(HELP_TEXT)
    exit(code)
end

"""
    parse_cli_args(argv::Vector{String}) -> CLIArgs

Hand-rolled CLI parser; see `--help` for the option list.
"""
function parse_cli_args(argv::Vector{String})::CLIArgs
    if isempty(argv) || "-h" in argv || "--help" in argv
        print_help_and_exit(0)
    end

    positional = String[]
    sbound = nothing
    outfile = nothing
    max_tries = nothing
    seed = nothing
    allow_factor = false

    i = 1
    n = length(argv)
    while i <= n
        a = argv[i]
        if a == "--sbound"
            i < n || error("--sbound requires a value")
            sbound = parse(Int, argv[i+1]); i += 2
        elseif a == "--outfile"
            i < n || error("--outfile requires a value")
            outfile = argv[i+1]; i += 2
        elseif a == "--max-tries"
            i < n || error("--max-tries requires a value")
            max_tries = parse(Int, argv[i+1]); i += 2
        elseif a == "--seed"
            i < n || error("--seed requires a value")
            seed = parse(Int, argv[i+1]); i += 2
        elseif a == "--allow-factor"
            allow_factor = true; i += 1
        elseif a in ("-h", "--help")
            print_help_and_exit(0)
        elseif startswith(a, "--")
            error("unknown option: $a (use --help for usage)")
        else
            push!(positional, a); i += 1
        end
    end

    length(positional) == 2 ||
        error("expected exactly 2 positional arguments <p> <N>, got $(length(positional)). Use --help for usage.")

    p_str = positional[1]
    N = parse(Int, positional[2])
    N > 0 || error("N must be a positive integer; got $N")

    return CLIArgs(p_str, N, sbound, outfile, max_tries, seed, allow_factor)
end

"""
    main(argv::Vector{String}=ARGS)

CLI entry point. Parses arguments, validates p, generates N distinct
random polarizations, writes them to a file, and prints a short summary
(including a truncated preview of p itself, since it may be hundreds of
digits long).
"""
function main(argv::Vector{String}=ARGS)
    args = try
        parse_cli_args(argv)
    catch err
        println(stderr, "Error: ", sprint(showerror, err))
        print_help_and_exit(1)
    end

    pZ = try
        parse_p_expr(args.p_str)
    catch err
        println(stderr, "Error parsing p: ", sprint(showerror, err))
        exit(1)
    end

    println("p = ", shortZ(pZ; maxchars=80), "  (", ndigits(pZ, base=2), " bits)")
    println("Validating p is prime and ≡ 11 (mod 12) ...")
    t0 = time()
    pZ = try
        check_p_11mod12(pZ)
    catch err
        println(stderr, "Error: ", sprint(showerror, err))
        exit(1)
    end
    println("  ok (", round(time() - t0, digits=2), "s)")

    sbound = args.sbound
    if sbound === nothing
        sbound = suggest_sbound(pZ)
        println("No --sbound given; auto-picked sbound = ", sbound,
                " for a ", ndigits(pZ, base=2), "-bit p")
    end

    filepath = args.outfile === nothing ? default_output_filename(pZ, args.N) : args.outfile

    # Open and write the header up front, then stream each distinct
    # polarization into the file as soon as any thread finds it (flushed
    # immediately), rather than accumulating everything in memory and only
    # writing once every thread has finished. This means: (a) progress is
    # visible on disk while the run is still going, and (b) if the process
    # is killed or crashes partway through, everything found up to that
    # point is already safely on disk instead of lost.
    io = open(filepath, "w")
    println(io, "p = $pZ")
    println(io, "order basis: [1, i, (i+j)/2, (1+ij)/2]")
    println(io, "# Each line: u v w x y z")
    flush(io)

    println("Generating N = ", args.N, " distinct polarizations with sbound = ", sbound,
            "  [threads: ", Threads.nthreads(), "]")
    println("Writing incrementally to ", filepath, " as results are found ...")
    t1 = time()

    function on_new_result(idx::Int, H::Hermitian2x2ZZ)
        w, x, y, z = to_wxyz(H.a)
        println(io, "[$idx] $(H.u) $(H.v) $w $x $y $z")
        flush(io)
    end

    results = try
        generate_polarizations(pZ, args.N;
            sbound=sbound,
            max_tries=args.max_tries,
            allow_factor=args.allow_factor,
            base_seed=args.seed,
            on_new_result=on_new_result)
    catch err
        println(stderr, "Error during generation: ", sprint(showerror, err))
        println(stderr, "Partial results (if any) were already written to ", filepath)
        close(io)
        exit(1)
    end
    close(io)

    println("  generated ", length(results), " polarizations in ", round(time() - t1, digits=2), "s")
    println("Wrote ", length(results), " polarizations to ", filepath)
    return filepath
end

# Only auto-run when executed as a script (`julia polz_random.jl ...`),
# not when `include()`-d from the REPL or another file.
if abspath(PROGRAM_FILE) == @__FILE__
    main(ARGS)
end